#
# create database it;
# create user ituser@localhost identified by 'itpass';
# grant all privileges on it.* to ituser@localhost;
# flush privileges;

drop table if exists test_tbl;

create table test_tbl(
  pk1      int      not null,
  pk2      smallint not null default 75,
     constraint primary key test_tbl_pk(pk1, pk2),
  uuid1       binary(16) not null,           /* generated by the client always */
  uuid2       binary(16) not null,           /* generated by the client when null */
     constraint test_tbl_ak1 unique(uuid1),
     constraint test_tbl_ak2 unique(uuid2),
  created_ts  timestamp default current_timestamp not null,
  modified_ts timestamp default current_timestamp not null,
  vc_col      varchar(200),
  char_col    char(7),
  date_col    date,
  time_col    time,
  num_col     decimal(65, 30),
  float_col   float(15,8),
  double_col  double,
  bit17_val   bit(17),
  enum_col    enum('alpha', 'beta', 'gamma', 'delta', 'epsilon'),
  bool_col    boolean,
  null_col    text
);

