#
# create user ituser default tablespace users identified by itpass;
# grant connect, resource, select_catalog_role to ituser;
# alter user ituser quota unlimited on users;
#

drop table test_tbl
/

create table test_tbl(
  pk1      int       not null,
  pk2      smallint  default 75 not null,
     constraint test_tbl_pk primary key(pk1, pk2),
  uuid1       raw(16) not null,           /* generated by the client always */
  uuid2       raw(16) not null,           /* generated by the client when null */
     constraint test_tbl_ak1 unique(uuid1),
     constraint test_tbl_ak2 unique(uuid2),
  created_ts  timestamp    default current_timestamp    not null,  /* NB: second precision */
  modified_ts timestamp(6) default current_timestamp(6) not null,  /* nanosecond precision, hope that's enough */
  vc_col      varchar2(200),
  char_col    char(7),
  date_col    date,
  time_col    date,
  num_col     decimal(38, 20),
  float_col   float,
  double_col  double precision,
  bit17_val   int,
  enum_col    varchar2(20),
    constraint test_tbl_ck1 check(enum_col in('Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon')),
  bool_col    number(1),
    constraint test_tbl_ck2 check(bool_col in(0, 1)),
  null_col    varchar2(10)
)
/


# select * from test_tbl