#
# create user ituser with password 'itpass';
# create database it owner ituser;
#
# --
# create schema if not exists authorization ituser;
# grant all on schema ituser to ituser;
# grant all on database it to ituser;
# alter default privileges in schema ituser grant all on tables to ituser;
# alter role ituser set search_path = ituser,public;

drop table if exists test_tbl
/

create table test_tbl(
  pk1      int      not null,
  pk2      smallint not null default 75,
     constraint test_tbl_pk primary key(pk1, pk2),
  uuid1       uuid not null,           /* generated by the client always */
  uuid2       uuid not null,           /* generated by the client when null */
     constraint test_tbl_ak1 unique(uuid1),
     constraint test_tbl_ak2 unique(uuid2),
  created_ts  timestamp    default current_timestamp    not null,  /* NB: second precision */
  modified_ts timestamp(6) default current_timestamp(6) not null,  /* nanosecond precision, hope that's enough */
  vc_col      varchar(200),
  char_col    char(7),
  date_col    date,
  time_col    time,
  num_col     decimal(65, 30),
  float_col   real,
  double_col  double precision,
  bit17_val   int,  /* postgres support for using 'bit varying' with JDBC is mysterious */
  enum_col    varchar(20),
    constraint test_tbl_ck1 check(enum_col in('Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon')),
  bool_col    boolean,
  null_col    text
)
/

commit
